spring.application.name=dnd6.club
spring.main.banner-mode=off

spring.mvc.static-path-pattern = /**

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.id.new_generator_mappings = false
spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.use_sql_comments = true
spring.jpa.properties.hibernate.format_sql = true

server.error.whitelabel.enabled=false
server.error.path=/error
server.error.include-message=always

server.servlet.session.timeout = 30m
spring.profiles.active=local

#logging.level.org.springframework.security=DEBUG

auth-service.base-url=https://auth.api.ttg.club

online.api.url=${ONLINE_API_URL:}
online.api.token=${ONLINE_API_TOKEN:}
online.site-id=${ONLINE_SITE_ID:5e14}

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.displayRequestDuration=true

management.endpoints.web.exposure.include=*
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.[http.server.requests]=true

images.root=/mnt/images
images.token.borders=/tokens/borders

app.url=${APP_URL}
app.img.url=${APP_IMG_URL}

allowed-origin-patterns=ttg.club,*.ttg.club
