name: Deploy

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

permissions:
  deployments: write
  contents: read
  pages: write
  actions: write
  id-token: write

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-front:
    name: Frontend Build Workflow
    uses: ./.github/workflows/build-frontend.yml

  build:
    name: Build to Docker Hub
    needs: build-front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: TTG-Club/ttg-club-backend
          ref: ${{ github.ref_name }}

      - uses: actions/download-artifact@v4
        with:
          name: front-app-${{ github.run_id }}
          path: ./src/main/resources/static/

      - name: Copy SPA html
        run: mv ./src/main/resources/static/index.html ./src/main/resources/templates/spa.html

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 8
          cache: maven

      - name: Maven Install
        run: mvn -B clean install -DskipTests -Dfrontend.application.sha=

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: magistrus/dnd5club-${{ github.ref_name == 'dev' && 'dev' || 'prod' }}:latest

  restart-server:
    name: Update Server Workflow
    needs: build
    uses: ./.github/workflows/update-server.yml
    secrets: inherit
